laravel/routes/web.php
<?php

Auth::routes();

// Social login
Route::get('/login/{social}','Auth\LoginController@socialLogin')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/login/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');

//Image resize & crop on view:  http://image.intervention.io/
Route::get('/resize/{w}/{h}',function($w=null, $h=null){
  $img = Illuminate\Support\Facades\Input::get("img");
  return \Image::make(public_path(urldecode($img)))->fit($w, $h, function ($constraint) {
      $constraint->upsize();
  })->response('jpg');
 });

// Admin
Route::group(['as' => 'admin.', 'middleware' => 'roles','roles' =>['admin', 'sadmin'], 'namespace' => 'Admin', 'prefix' => 'admin'], function() {

    App::setLocale('ua');

    Route::put('ajax/status', ['as' => 'ajax.status', 'uses' => 'AjaxController@status']);
    Route::put('ajax/reorder', ['as' => 'ajax.reorder', 'uses' => 'AjaxController@reorder']);

    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::resource('user', 'UserController');
    Route::resource('page-category', 'PageCategoryController');
    Route::resource('page', 'PageController');
    Route::resource('doctor', 'DoctorController');
    Route::resource('slide', 'SlideController');
});



// SPA
Route::get('/{any}', function () {
    return view('front');
})->where('any', '.*');

laravel/app/Http/Controllers/Admin/SlideController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Slide;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;

class SlideController extends Controller
{
    public function index()
    {
        return view('admin.slide.index', [
            'page' => Slide::orderBy('order')->get()
        ]);
    }

    public function create()
    {
        return view('admin.slide.create', ['page' => new Slide]);
    }

    public function store(Request $request, Slide $slide)
    {
        $request->validate([
            'title' => 'required',
        ]);

        $slide = $slide->create($request->all());

        return redirect()->route('admin.slide.index')->with('success', 'Item created');
    }

    public function show(Slide $slide)
    {
        return view('admin.slide.show', ['page' => $slide]);
    }

    public function edit(Slide $slide)
    {
        return view('admin.slide.edit', ['page' => $slide]);
    }

    public function update(Request $request, Slide $slide)
    {
        $request->validate([
            'title' => 'required',
        ]);

        $data = $request->all();

        $slide->update($data);

        if (array_key_exists('redirect', $data)) return redirect()->route('admin.dashboard')->with('success', 'Item updated');

        return redirect()->route('admin.slide.index')->with('success', 'Item updated');
    }

    public function destroy(Slide $slide)
    {
        $slide->delete();

        return 'success';
    }
}

laravel/resources/views/admin/slide/create.blade.php
@extends('admin.layout')

@section('content')
<div class="card">
  <div class="card-header bg-light">
    <h3>@lang('message.slide')</h3>
  </div>

  <div class="card-body">

    {!! Form::open(['route' => ['admin.slide.store'], 'method' => 'POST']) !!}
      @include('admin.slide.form')
    {!! Form::close() !!}

  </div>
</div>

@endsection

laravel/resources/views/admin/slide/edit.blade.php
@extends('admin.layout')

@section('content')
<div class="card">
  <div class="card-header bg-light">
    <h3>@lang('message.slide')</h3>
  </div>

  <div class="card-body">

    {!! Form::open(['route' => ['admin.slide.update', $page->id], 'method' => 'PUT']) !!}
      @include('admin.slide.form')
    {!! Form::close() !!}

  </div>
</div>

@endsection

laravel/resources/views/admin/slide/form.blade.php
<div class="form-group row">
  <label for="title" class="col-sm-2 col-form-label">@lang('message.title')</label>
  <div class="col-sm-10">
    {!! Form::text('title', $page->title, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="form-group row">
  <label for="image" class="col-sm-2 col-form-label">@lang('message.image')</label>
  <div class="col-sm-10">
    <img id="holder" style="margin-top:15px;max-height:100px;" src="{{ $page->image }}">
    <a id="lfm" data-input="thumbnail" data-preview="holder" class="lfm btn btn-primary">
      <i class="icon icon-picture"></i> @lang('message.select')
    </a>
    <a id="delete-image" class="btn btn-danger {{($page->image) ? '' : 'hidden'}}">
      <i class="icon icon-trash"></i> @lang('message.delete')
    </a>
  </div>
  <input id="thumbnail" class="form-control" type="hidden" name="image" value="{{ $page->image }}">
</div>

<div class="form-group row">
  <label for="link" class="col-sm-2 col-form-label">@lang('message.link')</label>
  <div class="col-sm-10">
    {!! Form::text('link', $page->link, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="toggle-switch" data-ts-color="primary">
  {!! Form::hidden('published', 0) !!}
  <label for="published" class="ts-label">@lang('message.published')</label>
  {!! Form::checkbox('published', 1, $page->published, ['id' => 'published']) !!}
  <label for="published" class="ts-helper"></label>
</div>

<hr>


<button type="submit" class="btn btn-success">
  <i class="fa fa-download"></i> &nbsp; @lang('message.save')
</button>

laravel/resources/views/admin/slide/index.blade.php
@extends('admin.layout')

@section('content')

<div class="card">
  <div class="card-header bg-light">
    <h3>@lang('message.slide')</h3>
    <div>
      <a href="{{ route('admin.slide.create') }}" class="btn btn-light"><i class="fa fa-plus-square-o"></i> @lang('message.create')</a>
    </div>
  </div>

  <div class="card-body" style="position: relative;">
    <div class="table-responsive">
      <table class="table text-center sorted_table" model="Slide">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">actions</th>
            <th scope="col">@lang('message.title')</th>
            <th scope="col">@lang('message.link')</th>
            <th scope="col">@lang('message.image')</th>
            <th scope="col">@lang('message.published')</th>
          </tr>
        </thead>
        <tbody>

          @foreach($page as $item)
          <tr data-id="{{$item->id}}">
            <th scope="row">{{$item->id}}</th>
            <td>
              <a href="{{ route('admin.slide.edit', $item->id) }}" title="Edit"><i class="fa fa-edit"></i></a>
              &nbsp;&nbsp;&nbsp;
              <a href="{{ route('admin.slide.destroy', $item->id) }}" title="Delete" class="delete-item"><i class="fa fa-trash-o"></i></a>
            </td>
            <td>{{$item->title}}</td>
            <td>{{$item->link}}</td>
            <td><img src="/resize/50/40/?img={{urlencode($item->image)}}"></td>
            <td>
              <a href="{{route('admin.ajax.status', ['id' => $item->id, 'model' => 'Slide', 'field' => 'published'])}}" class="status fa fa-{{$item->published ? 'check-circle' : 'times-circle'}}"></a>
            </td>
          </tr>
          @endforeach

        </tbody>
      </table>
    </div>
  </div>

</div>

@endsection